workflows:
  zvhive-android:
    name: ZVHive Android Build
    environment:
      groups:
        - env_vars
      vars:
        APP_NAME: "ZVHive"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up Flutter
        script: |
          flutter --version
          flutter channel stable
          flutter upgrade
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Run tests
        script: |
          flutter test
      - name: Build Android APK
        script: |
          flutter build apk --release --dart-define=SUPABASE_URL=$SUPABASE_URL --dart-define=SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY --dart-define=ADMOB_APP_ID=$ADMOB_APP_ID --dart-define=ADMOB_BANNER_ID=$ADMOB_BANNER_ID --dart-define=ADMOB_INTERSTITIAL_ID=$ADMOB_INTERSTITIAL_ID
    artifacts:
      - build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - zvhivecorp@gmail.com
        notify:
          success: true
          failure: true